### ISSUE TITLE
Check for use of hard_coded facility_type numbers on links

### ISSUE THREAD

**Issue by ssmith55** [VolpeUSDOT/RDR-Public#6]
This issue is motivated by discussion with H-GAC.  The config file for format_network indicates that centroid_connectors should have facility_type = 11.  Some agencies may be using a different facility type for these links.  Check if the '11' is hard coded, or can be a configuration item.  Same question for the hard coded transit link types of 21,22,23,25  (although the latter may be hardcoded in gtfs2gmns).  @kzhang81 , @ssmith55

**Comment by kzhang81** [comment]
Thanks @ssmith55 for noting this! The facility_type numbers are currently hard-coded (and if the user is using the default repair cost and time tables, these specific numbers are required). I will make a note of this internally and we can explore creating a more flexible customization of this for users. (As mentioned, we will need to investigate how to adapt the GTFS2GMNS tool as well.)
